// NEVER CHANGE THIS SCRIPT EVER
package frc.robot;
// NEVER CHANGE THIS SCRIPT EVER
import edu.wpi.first.wpilibj.RobotBase;
// NEVER CHANGE THIS SCRIPT EVER
public final class Main {
  private Main() {
  }
  // NEVER CHANGE THIS SCRIPT EVER
  public static void main(String... args) {
    RobotBase.startRobot(Robot::new);
  }
}
// NEVER CHANGE THIS SCRIPT EVER
// NEVER CHANGE THIS SCRIPT EVER
// NEVER CHANGE THIS SCRIPT EVER
// NEVER CHANGE THIS SCRIPT EVER
// NEVER CHANGE THIS SCRIPT EVER
// NEVER CHANGE THIS SCRIPT EVER
// NEVER CHANGE THIS SCRIPT EVER
// NEVER CHANGE THIS SCRIPT EVER
// NEVER CHANGE THIS SCRIPT EVER
