
/// xkxdolc:cloddddddddddooooollllllllllclxkddxxdxxoldkxddxxkdxxxdllllcc::::ccc:::c:cc::::::::::::::::cc
/// looc::::clodddooooolllcc::::::::::;:;l00k00000Od:kN0xOOO0xOXKx:ccccccccccccccccccccc:::::::::::ccccc
/// ;:;;:::::cccllllccc:::;;;;;;;;;;;;;;,ckocx0kkOOx:dXkokxx0kkOOdcccccclllllllllllllllcccccccccccccccll
/// ;;;;:::::::::cc::;;;;;;;;;,,,,,,,''''',,',:;;:c:;;::;::clcccllccccc::ccccccccccccclllllllllllllllooo
/// ;;:::::::;;;;;;;;,,,,,,,,,,'''''.......................';;:cllollllc:;;,',''''',',,;:::ccccllooooooo
/// ::::;;;;,,,,,,,,,,'''''''''''.......................',;:cloooooddddddool:;;,,''''''',;;;;::cccclllll
/// :;;;,,,,,,,,,,''''''............................';;:cllllooooooddddddddollc:;;,''''',,,,;;;:::::cccc
/// ,,,,'''''''''''''............................';:clllllllooloooooooooooooollccc:;,,,''',,,,;;;:::::::
/// ''''''''''''''............................';:cllllllllllooooooooooooolllllllllc:;;;,,,,,,,,;;;::::::
/// '''....................................',:cllllolloooollloooooooooollllllllolllccc:;;,,,,,,,;;;;::::
/// .....................................,:cllloooollllllllllllloooolllllloooooooolllcc::;,,,,,,,;;;::::
/// .................................',;cllolooooooollllllllllllllllllllllooddooooolllcc:;;,,,,,,;;;;:::
/// .............................',;:cllllooooooooooollllloooddolcccccccclloooooollllcccc:;;,,,,,,,;;;;;
/// ...........................,:clllllllloooooooooooooooddxxxdlc:::::ccccclllllllcccccccc::;,,,,,,,,,;;
/// .........................':looolooooooooooooooollooodddxdoc;,''',;:::::cccccccccccccccc::;;,,,,,,,,;
/// .......................';clooooooooooolllllllllooooooddooc;,,,'.',;::::::::::::::::cccccc::;,,,,,,,;
/// .......................:looooooooolllllllllllllloooooolllc:ldc...',;;;;:::::::::::::cccccc:;,,,,,,,,
/// ........    ..........,clooooolllllllcccccccllllllollc::::ckk;....,;;;;::::ccc::::::cccccc:;;;;,,,,,
///              .........;cloolllllccccccccccccccclllllc:;;,;lxo'....';;;;::::ccc:::::::ccccc::;;;;;;;;
///               .......,:clllllllccccc:::::::::cccccccc:;,',cdl'...',;;;;::::cccc:::::::::ccc:;;;;;;;;
///           .   . ....';clllollllccccc::::::::::::::::::;,,,;:,..',;;;;;;;:::cccc:::::::::ccc::;;;;;;;
///              ......':loooollllllcccccc:::::::::;;;;;;;;;,,,,'.',,;;;;;;;:::ccccc::::::::ccc::;;;;;;:
///              ....':ldxdddooooollllllllccccc:::;;;;;;;;;;;;,,''',,,;;;;;::::cccccc:::::::ccc::::;;:::
///            ....':dxkkxxddddooooooooolllllllc::::;;;;;;;;;;;;,,,,,;;;;::cccclllllcc::::::cccc::::::::
///         .  ...;dkOOkkxxxdddddooooooollllooollcc::;;;;;;;;:::cccc:::ccllollllllllcc::;;;:cccc::::::::
///            ..cxO0Okkxxxdddooooooolllllllloooddol::;;;;;;;::ccllccllodddoolllllccc::;;;;:cccc:::;::::
///            .:xOOOxxddoooollllllcccccccccclodxxxdlc::;;;;;:::ccccllodddollccccccc:;;;;;;:cclcc:::::::
///         ...,oxxxdolcccccccc:::::;;,,,,,'',:ldkkxdllc::::::ccclllllooollcc:::::::;;;;;;;:ccllc:::::::
///           .,oddolc::::;;;;;;;,,,'..........;lxkkxdollcccclooooooolllcc:::;:::;;;;;;;;;::cllllc::::::
///           .,lddlc:::;;;;,,,,,,,'...........':dxkxdoollloodxxxxdollc:::;;;;;;;;;;;;;;;;:codddolc:::::
///           .'coolcc:::;;;;;;;,,,'............,ldxxdoollldxxkkxxdolc:;;;,,,,,,,,,,,,,;;:codxxdolc:::::
///            .':clcc::::;;;;:;;,,''...........':loddoollloxkkkkxdol:;;,,,,,,,,,,,,,,,,;coxkxdollccccc:
///            ..':ccc::::;;;;:;;,,'''''........',:loooollodxxxxddol:;;,,,,,,,,,,,''',,;coxxxdlllccccccc
///             ..,::c:::::::;;;;;,,''''''.....'',:clooooooddoolllc:;;,,,,,,''''''''',;clddollc::ccccccc
///             ...,::c:::::::;;;;,,,,,,,,,,,,,;;:cllooodoooolllcc::;;;,,,,,'''''''',;cloolc:;;;;;:::::c
///            .....',;;::cc::;::;;;;;;;;;;:::ccccllooddddoolllllc::;;;,,,'''''..'',;:cc:::;,,,,,,,,,,,,
///           ..........';:cc:::::;;;:::::cccllllloooddddooolllllc:;;;;,,'''....',;;:;;;,,,,''''''''''''
/// ........ ............';cllccc:::::cclllllooloooodddddoooooolc;;;;;,,''''''',,;:;,,,'''''''''''''''''
/// ......................,codollccccllooooodooooooddxxxxddddxdo:,,,,''...'',;;;;;,,'''''''.............
/// ......................':dxxddollloddxxxxxddddddxxkkkkkkxxxdc,''''....'',,,,,,''''...................
/// .......................:dkkxxdooodxxkkkkxxxxxxxxkOOOOOkkxoc,''......................................
/// .......................'lxkkkxddxxkkkkkkkkkxxxxkOOOOOOkxo:'.........................................
/// ........................,lxkkkkxxkkkkkkkkkkkkkkkOOOOOOxl,.....              ........................
/// .........................;lxkkkkkkkkkOOOOOOOOOOOkkkkkxc'...                        .................
/// ..........................,lxkkkOOOOO00000000OOOkkxxoc'.                                ............
/// .......................   .'coxkkOOOO0000000OOkxxolc;...                                        ....
/// .........................  ..';clodddxxxxxxxdolc;'.....                                           ..
/// ........................  .......',,,,,,,;;,,'...                                                ...
///   ........................... .;l:;cc;:l:,cl;:c,:cc;,::..::;;;c;,;:;.                            ...
///   ........................ .. .dKdx POGGERS FISH           oOXk.                            ...
///   ......................      .lo.;xkookdoxkoddcoxxl:dk,.d::o:dkodko.                            ...
///   ..................           .. .''..'...'..'......''.......''.....                              .
/// 
//    ___  ___   ___   ___ ___ ___ _  _ 
//   | _ \/ _ \ / __| | __|_ _/ __| || |
//   |  _/ (_) | (_ | | _| | |\__ \ __ |
//   |_|  \___/ \___| |_| |___|___/_||_|
//                           
//    ___  ___   ___  ___ ___ ___  ___   ___ ___ ___ _  _ 
//   | _ \/ _ \ / __|/ __| __| _ \/ __| | __|_ _/ __| || |
//   |  _/ (_) | (_ | (_ | _||   /\__ \ | _| | |\__ \ __ |
//   |_|  \___/ \___|\___|___|_|_\|___/ |_| |___|___/_||_|
//  